// ---- Expanded word bank ----
export const WORD_BANK: Record<string, string[]> = {
  "Gen Z Vibes": [
    "rizz", "slay", "bussin", "delulu", "stan", "simp", "mid", "bestie", "purr",
    "sheesh", "unhinged", "gaslight", "gatekeep", "girlboss", "periodt", "respectfully",
    "situationship", "aesthetic", "vibe", "cringe", "basic", "salty", "shook", "sus",
    "tea", "flex", "clout", "fire", "lowkey", "highkey", "ghosting", "finsta",
    "FOMO", "GOAT", "lit", "savage", "shade", "thirsty", "woke", "yeet", "cap"
  ],
  "Psychedelic Trip": [
    "fractal", "kaleidoscope", "mandala", "chakra", "vibration", "enlightenment", "oneness",
    "transcendence", "portal", "spiral", "infinity", "cosmos", "dimension", "frequency",
    "energy", "aura", "crystal", "prism", "vortex", "nebula", "galaxy", "stardust",
    "moonbeam", "sunburst", "rainbow", "aurora", "mirage", "illusion", "vision", "dreamscape",
    "trance", "meditation", "nirvana", "bliss", "harmony", "unity", "consciousness", "awakening",
    "metamorphosis", "rebirth", "euphoria", "serenity"
  ],
  "Viral Internet": [
    "meme", "viral", "trending", "algorithm", "influencer", "aesthetic", "timeline", "multiverse",
    "speedrun", "cursed", "blessed", "chaotic", "cottagecore", "goblincore", "weirdcore",
    "traumacore", "vaporwave", "hyperpop", "girlhood", "boyhood", "adulting", "NPC",
    "main character", "side quest", "lore", "canon", "cringe", "based", "ratio", "stan",
    "simp", "touch grass", "chronically online", "unhinged", "feral", "goblin mode", "delulu",
    "rizz", "aura", "edgy", "softcore", "hardcore"
  ],
  "Fantasy Realms": [
    "dragon", "unicorn", "phoenix", "griffin", "basilisk", "chimera", "hydra", "pegasus", "centaur",
    "mermaid", "fairy", "elf", "dwarf", "goblin", "troll", "ogre", "orc", "wizard", "sorcerer",
    "witch", "warlock", "necromancer", "paladin", "ranger", "rogue", "bard", "druid", "monk",
    "wand", "staff", "amulet", "sword", "shield", "armor", "potion", "spell", "quest", "prophecy",
    "crystal", "dungeon", "castle"
  ],
  "Street Food": [
    "tacos", "churros", "empanadas", "samosas", "gyros", "shawarma", "kebabs", "takoyaki",
    "okonomiyaki", "elote", "arepas", "pupusas", "pho", "dumplings", "poutine", "roti",
    "crepes", "beignets", "falafel", "quesadilla", "burritos", "nachos", "pretzel", "corndog",
    "funnel cake", "waffle", "cronut", "donut", "bagel", "mochi", "bao", "tamale",
    "chimichanga", "tostada", "flautas", "gordita", "sope", "esquite", "chicharron", "churro", "bunuelo"
  ],
  "Retro Gaming": [
    "powerup", "checkpoint", "respawn", "fatality", "combo", "joystick", "controller",
    "cartridge", "pixel", "sprite", "noob", "pwned", "camping", "griefing", "loot",
    "boss", "health bar", "mana", "continue", "game over", "insert coin", "arcade",
    "highscore", "cheatcode", "speedrun", "glitch", "mod", "emulator", "ROM", "console",
    "platform", "sidescroller", "dungeon", "quest", "inventory", "save", "load", "pause", "warp", "secret", "bonus"
  ],
  "Space Odyssey": [
    "nebula", "quasar", "pulsar", "supernova", "wormhole", "asteroid", "comet", "meteor",
    "satellite", "starship", "rocket", "galaxy", "cosmos", "void", "orbit", "launch",
    "spacewalk", "alien", "exoplanet", "eclipse", "constellation", "antimatter", "hyperspace",
    "cryosleep", "terraforming", "moonbase", "colony", "spacecraft", "shuttle", "probe",
    "aurora", "solar", "lunar", "stellar", "cosmic", "astral", "celestial", "interstellar", "zero gravity", "stardust", "blackhole"
  ],
  "Urban Legends": [
    "Bigfoot", "Mothman", "Chupacabra", "Slenderman", "wendigo", "banshee", "poltergeist",
    "skinwalker", "cryptid", "phantom", "specter", "apparition", "haunting", "possession",
    "curse", "hex", "omen", "ritual", "séance", "ouija", "cemetery", "graveyard",
    "tombstone", "crypt", "mausoleum", "coffin", "ghost", "spirit", "shadow", "entity",
    "demon", "vampire", "werewolf", "zombie", "ghoul", "monster", "creature", "beast", "legend", "myth", "folklore"
  ],
  "Coffee Culture": [
    "espresso", "cappuccino", "latte", "macchiato", "americano", "mocha", "frappe",
    "cortado", "affogato", "ristretto", "barista", "brew", "roast", "beans", "grind",
    "steam", "foam", "crema", "drip", "pour", "French press", "AeroPress", "siphon",
    "Turkish", "Vietnamese", "Irish", "iced", "cold brew", "nitro", "oat milk", "almond milk",
    "soy milk", "vanilla", "caramel", "hazelnut", "cinnamon", "chocolate", "whipped cream", "sprinkles", "syrup", "sugar"
  ],
  "Extreme Sports": [
    "parkour", "skydiving", "snowboarding", "skateboarding", "surfing", "wakeboarding",
    "BMX", "motocross", "kayaking", "rafting", "climbing", "bungee", "wingsuit",
    "paragliding", "kitesurfing", "slacklining", "highlining", "drifting", "rally",
    "downhill", "freeride", "halfpipe", "ramp", "grind", "ollie", "kickflip", "backflip",
    "frontflip", "aerial", "trick", "stunt", "jump", "drop", "carve", "shred", "gnarly",
    "radical", "tube", "barrel", "wave", "powder"
  ],
  "Mystical Artifacts": [
    "crystal", "tarot", "runes", "pendulum", "dreamcatcher", "cauldron", "grimoire",
    "athame", "chalice", "pentacle", "wand", "orb", "amulet", "talisman", "charm",
    "scroll", "tome", "spell", "potion", "elixir", "incense", "sage", "smudge",
    "candle", "altar", "offering", "ritual", "divination", "scrying", "mirror",
    "geode", "quartz", "amethyst", "obsidian", "moonstone", "selenite", "jade", "turquoise", "opal", "ruby"
  ],
  "Dystopian Future": [
    "cyberpunk", "neon", "hologram", "implant", "cyborg", "android", "robot", "drone",
    "AI", "algorithm", "surveillance", "corporation", "wasteland", "bunker", "vault",
    "radiation", "mutant", "clone", "synthetic", "virtual", "matrix", "grid", "network",
    "firewall", "hack", "virus", "malware", "glitch", "crash", "reboot", "upgrade",
    "augment", "biometric", "scanner", "chip", "code", "data", "upload", "download", "server"
  ],
  "Comfort Things": [
    "blanket", "pillow", "hoodie", "slippers", "robe", "candle", "tea", "coffee",
    "chocolate", "cookies", "soup", "fireplace", "hammock", "swing", "nap", "cuddle",
    "snuggle", "cozy", "warm", "soft", "fuzzy", "plush", "teddy", "book", "movie",
    "music", "rain", "snow", "autumn", "sweater", "scarf", "mittens", "socks", "pajamas",
    "bath", "bubble", "aromatherapy", "lavender", "vanilla", "cinnamon", "nostalgia"
  ],
  "Ocean Mysteries": [
    "kraken", "megalodon", "leviathan", "serpent", "mermaid", "siren", "shipwreck",
    "treasure", "atlantis", "abyss", "trench", "reef", "kelp", "jellyfish", "squid",
    "octopus", "anglerfish", "shark", "whale", "dolphin", "narwhal", "seahorse", "starfish",
    "coral", "pearl", "shell", "tsunami", "whirlpool", "maelstrom", "tide", "current",
    "wave", "depth", "submarine", "anchor", "lighthouse", "buoy", "sailor", "pirate", "mariner"
  ],
  "Cozy Aesthetics": [
    "cottagecore", "grandmacore", "bookshelf", "teacup", "vintage", "antique", "rustic",
    "farmhouse", "cottage", "cabin", "hearth", "quilt", "knitting", "crochet", "embroidery",
    "lace", "floral", "botanical", "garden", "greenhouse", "windowsill", "plants", "herbs",
    "wildflower", "daisy", "rose", "lavender", "honeysuckle", "mushroom", "moss", "fern",
    "basket", "wicker", "pottery", "ceramic", "handmade", "homemade", "baking", "bread", "jam", "honey"
  ],
  "Indian": [
    "Bollywood", "chai", "dosa", "biryani", "samosa", "naan", "paneer", "curry",
    "tandoor", "masala", "tikka", "kebab", "lassi", "gulab jamun", "jalebi", "kulfi",
    "diwali", "holi", "rangoli", "mehndi", "saree", "kurta", "dhoti", "bindi",
    "tabla", "sitar", "harmonium", "dhol", "bhangra", "kathak", "namaste", "yoga",
    "mandir", "taj mahal", "rickshaw", "bazaar", "monsoon", "cricket", "maharaja", "rajput",
    "hindi", "punjabi", "bengali", "tamil"
  ]
}

export const ALL_CATEGORIES = Object.keys(WORD_BANK)

// ---- Impostor hints ----
// One subtle, hand-authored clue per word. The impostor sees the hint for the
// chosen word so they can bluff — evocative enough to catch the vibe, never the answer.
export const WORD_HINTS: Record<string, string> = {
  "rizz": "That effortless pull that lands the crush",
  "slay": "When you absolutely crushed the look",
  "bussin": "Kitchen praise for something dangerously tasty",
  "delulu": "Believing the fantasy against all evidence",
  "stan": "Loyalty to a fave bordering on obsessive",
  "simp": "Doing way too much for one crush",
  "mid": "Landing squarely in forgettable territory",
  "bestie": "Your ride-or-die on speed dial",
  "purr": "A soft feline sound of approval",
  "sheesh": "That drawn-out gasp when something impresses",
  "unhinged": "Behavior with the safety latch removed",
  "gaslight": "Making someone doubt their own memory",
  "gatekeep": "Hoarding the cool thing from newcomers",
  "girlboss": "Corner-office energy with a hustle caption",
  "periodt": "End of discussion, with extra attitude",
  "respectfully": "Politeness worn as a shield before shade",
  "situationship": "Almost dating but nobody said so",
  "aesthetic": "A curated look with a consistent mood",
  "vibe": "The unspoken mood filling a room",
  "cringe": "That secondhand full-body wince",
  "basic": "Loving only the mainstream default stuff",
  "salty": "Sourly bitter after a small loss",
  "shook": "Rattled to your core by surprise",
  "sus": "Something quietly off about them",
  "tea": "The juicy gossip everyone leans in for",
  "flex": "Showing off the win a little loudly",
  "clout": "Chasing influence for the follower count",
  "fire": "So good it practically blazes",
  "lowkey": "Kept quiet and under the radar",
  "highkey": "Loudly, no hiding it at all",
  "ghosting": "When the replies just stop, forever",
  "finsta": "The secret account for close friends only",
  "FOMO": "That ache of missing the party",
  "GOAT": "The undisputed best to ever do it",
  "lit": "When the party truly ignites",
  "savage": "Ruthless with zero apology given",
  "shade": "A compliment sharpened into an insult",
  "thirsty": "Desperate for attention, painfully obvious",
  "woke": "Alert to injustice, sometimes performatively",
  "yeet": "Hurling something with wild force",
  "cap": "Calling out the lie behind it",
  "fractal": "Zoom in forever and it repeats",
  "kaleidoscope": "Twist the tube, symmetry shatters and reforms",
  "mandala": "A circular pattern that pulls you inward",
  "chakra": "Spinning wheels along the spine",
  "vibration": "Everything hums at its own pitch",
  "enlightenment": "The sudden click where it all makes sense",
  "oneness": "No more edges between you and everything",
  "transcendence": "Rising past the ordinary self",
  "portal": "A doorway that shouldn't be there",
  "spiral": "Winding inward, never quite arriving",
  "infinity": "No edges, no end, just more",
  "cosmos": "The whole grand ordered everything above",
  "dimension": "A layer of reality just next door",
  "frequency": "Tune the dial and reality shifts",
  "energy": "The invisible current running through it all",
  "aura": "The colored glow some claim to see",
  "crystal": "A faceted stone said to hold power",
  "prism": "Light walks in white, exits striped",
  "vortex": "A swirling pull you cannot resist",
  "nebula": "A glowing cloud where stars are born",
  "galaxy": "A vast pinwheel of countless suns",
  "stardust": "The glittering leftovers of dead suns",
  "moonbeam": "Pale light sliding down at night",
  "sunburst": "Rays exploding outward from one hot center",
  "rainbow": "Seven bands arcing after the rain",
  "aurora": "Curtains of color dancing near the poles",
  "mirage": "Shimmering water that isn't really there",
  "illusion": "Your eyes swear to a lie",
  "vision": "A scene that arrives behind closed eyes",
  "dreamscape": "The strange landscape you wander while sleeping",
  "trance": "Half-gone, swaying somewhere far away",
  "meditation": "Sitting still and watching the breath",
  "nirvana": "The final quiet where craving ends",
  "bliss": "Pure joy with nothing else attached",
  "harmony": "When every part hums together right",
  "unity": "Many things melting into one",
  "consciousness": "The lit-up awareness of being here",
  "awakening": "Eyes opening to what was always there",
  "metamorphosis": "The caterpillar's whole-body rewrite",
  "rebirth": "Coming back new after the old ends",
  "euphoria": "A soaring rush that lifts everything",
  "serenity": "Calm so deep the surface goes glassy",
  "meme": "A joke that copy-pastes across the web",
  "viral": "Spreading faster than anyone planned",
  "trending": "Bubbling up the charts right now",
  "algorithm": "The invisible hand feeding your feed",
  "influencer": "Paid to make you want things",
  "timeline": "The endless scroll of everyone's posts",
  "multiverse": "Every choice spawns another version of you",
  "speedrun": "Racing the clock to finish fast",
  "cursed": "An image you cannot unsee",
  "blessed": "Wholesome content for your soul",
  "chaotic": "No rules, pure gremlin energy",
  "cottagecore": "Baking bread in a soft meadow fantasy",
  "goblincore": "Mud, mushrooms, and shiny little treasures",
  "weirdcore": "Uncanny liminal dreamscapes that unsettle",
  "traumacore": "Nostalgia laced with quiet pain",
  "vaporwave": "Pink sunsets and dead mall Muzak",
  "hyperpop": "Pop cranked past the red line",
  "girlhood": "Glitter, diaries, and coming-of-age softness",
  "boyhood": "Scraped knees and growing-up nostalgia",
  "adulting": "Taxes and dishes nobody prepared you for",
  "NPC": "Standing there repeating the same line",
  "main character": "Acting like the whole world watches you",
  "side quest": "A fun detour off the main path",
  "lore": "The deep backstory only fans know",
  "canon": "What officially counts in the story",
  "based": "Boldly saying what you actually think",
  "ratio": "When the replies bury the original",
  "touch grass": "Advice to log off and go outside",
  "chronically online": "Brain rewired by too much scrolling",
  "feral": "Gone wild, all restraint abandoned",
  "goblin mode": "Embracing your grimiest lazy self",
  "edgy": "Trying hard to seem dangerous",
  "softcore": "The mild, gentle end of the spectrum",
  "hardcore": "The extreme, no-mercy end of the spectrum",
  "dragon": "A hoard-guarding beast that breathes fire",
  "unicorn": "A pure white steed with one point",
  "phoenix": "Born again from its own ashes",
  "griffin": "Half king of beasts, half king of skies",
  "basilisk": "One glance from it turns you to stone",
  "chimera": "A patchwork monster of mismatched parts",
  "hydra": "Cut one off, two grow back",
  "pegasus": "A galloping steed with feathered flight",
  "centaur": "Half rider, half the horse itself",
  "mermaid": "She sings from the waves below",
  "fairy": "Tiny, winged, and fond of mischief",
  "elf": "Pointed ears and ageless woodland grace",
  "dwarf": "Short, bearded, and at home underground",
  "goblin": "A small, greedy cave-dwelling pest",
  "troll": "Lumbering brute lurking under the bridge",
  "ogre": "A giant, dim-witted, hungry brute",
  "orc": "Green-skinned foot soldier of dark armies",
  "wizard": "Robed, bearded, and full of arcane knowledge",
  "sorcerer": "Raw magic runs in their blood",
  "witch": "She brews trouble over a bubbling pot",
  "warlock": "A male dabbler in the darker arts",
  "necromancer": "He wakes what should stay buried",
  "paladin": "A holy knight sworn to the light",
  "ranger": "A lone tracker at home in the wild",
  "rogue": "Sticks to shadows, picks a pocket",
  "bard": "Songs and stories are their weapon",
  "druid": "Nature's keeper who shapes wild forms",
  "monk": "Bare fists and inner discipline",
  "wand": "A slender stick that channels magic",
  "staff": "A tall walking aid crackling with power",
  "amulet": "Worn at the neck for protection",
  "sword": "A blade drawn for the duel",
  "shield": "Raised to catch the incoming blow",
  "armor": "Metal worn to turn aside blades",
  "potion": "A little bottle you drink for effects",
  "spell": "A few words that bend reality",
  "quest": "A long journey toward one goal",
  "prophecy": "Foretold words the hero must fulfill",
  "dungeon": "A dark maze below, full of danger",
  "castle": "High stone walls and a throne within",
  "tacos": "Folded and handheld, south of the border",
  "churros": "Ridged, fried, and dusted with sweetness",
  "empanadas": "A pocket you can hold, filling tucked inside",
  "samosas": "A crispy triangle from the subcontinent",
  "gyros": "Shaved off a spinning vertical stack",
  "shawarma": "Wrapped meat carved from a turning column",
  "kebabs": "Threaded on skewers over open flame",
  "takoyaki": "Round griddled bites from a Japanese stall",
  "okonomiyaki": "A savory griddle-cooked disc, your way",
  "elote": "On a stick, slathered and grilled, Mexican fair",
  "arepas": "A split cornmeal round, filled and warm",
  "pupusas": "Stuffed griddle cakes from El Salvador",
  "pho": "A steaming Vietnamese bowl of noodles",
  "dumplings": "Little wrapped parcels, steamed or pan-fried",
  "poutine": "A messy Canadian pile with gravy",
  "roti": "A flat griddled bread, torn and dipped",
  "crepes": "Paper-thin and folded, sweet or savory",
  "beignets": "Pillowy fried squares under powdered snow",
  "falafel": "Crispy chickpea spheres from the Middle East",
  "quesadilla": "Folded and toasted, oozing when pulled apart",
  "burritos": "A big wrapped bundle you eat by hand",
  "nachos": "A shared pile, loaded and topped generously",
  "pretzel": "A knotted, salted twist from the cart",
  "corndog": "Battered and fried, served on a stick",
  "funnel cake": "A fried tangle showered in sweet dust",
  "waffle": "Grid-patterned pockets, crisp and golden",
  "cronut": "A trendy hybrid pastry, flaky and fried",
  "donut": "A sweet ring with a hole",
  "bagel": "A dense chewy ring, boiled then baked",
  "mochi": "Chewy pounded rice, soft and squishy",
  "bao": "A pillowy steamed bun, folded around filling",
  "tamale": "Steamed and unwrapped from its husk",
  "chimichanga": "A deep-fried wrapped bundle, Tex-Mex style",
  "tostada": "A flat crunchy base piled high",
  "flautas": "Rolled tight and fried until crisp",
  "gordita": "A thick stuffed pocket of masa",
  "sope": "A thick round with pinched-up edges",
  "esquite": "Kernels in a cup, dressed and spooned",
  "chicharron": "Crackling fried pork, crunchy and rich",
  "churro": "A single ridged fried stick, sugared",
  "bunuelo": "A thin fried disc, crisp and sweet",
  "powerup": "Grab it and you feel unstoppable",
  "checkpoint": "A safe spot to pick up from",
  "respawn": "Death is only temporary here",
  "fatality": "The finishing move that ends them brutally",
  "combo": "Chain the hits without a pause",
  "joystick": "Wiggle the stick, thumb on button",
  "controller": "Two hands, many buttons, tethered by cord",
  "cartridge": "Blow the dust before it works",
  "pixel": "The tiniest square on an old screen",
  "sprite": "A flat little character drawn in dots",
  "noob": "Fresh player who clearly has no clue",
  "pwned": "Utterly wrecked and taunted for it",
  "camping": "Lurking in one spot for easy kills",
  "griefing": "Ruining the fun on purpose",
  "loot": "The shiny drops after a fight",
  "boss": "The big menace guarding the exit",
  "health bar": "That colored strip draining toward doom",
  "mana": "Blue fuel for casting your spells",
  "continue": "Ten seconds to keep going or quit",
  "game over": "Two grim words on a dark screen",
  "insert coin": "Feed the slot to keep playing",
  "arcade": "A dark room humming with cabinets",
  "highscore": "Three initials at the top of the list",
  "cheatcode": "Up up down down and secrets unlock",
  "glitch": "A weird bug you can actually exploit",
  "mod": "Fan-made tweak to the original game",
  "emulator": "Software pretending to be old hardware",
  "ROM": "The game copied into a single file",
  "console": "The box under your TV for gaming",
  "platform": "Hop across gaps and floating ledges",
  "sidescroller": "The action rolls left to right",
  "inventory": "Your pockets full of collected gear",
  "save": "Lock in progress before you stop",
  "load": "Pull your progress back from before",
  "pause": "Freeze it all to grab a snack",
  "warp": "Skip ahead through a hidden shortcut",
  "secret": "Hidden thing tucked off the main path",
  "bonus": "Extra reward beyond the main goal",
  "quasar": "Blindingly bright beacon from a galaxy's hungry core",
  "pulsar": "A spinning beacon ticking like clockwork in space",
  "supernova": "When a dying star goes out screaming",
  "wormhole": "A cosmic shortcut folding two points together",
  "asteroid": "Lumpy space rock drifting in a belt",
  "comet": "An icy wanderer trailing a glowing tail",
  "meteor": "A streak of fire crossing the night sky",
  "satellite": "Something circling, keeping quiet watch above",
  "starship": "A grand vessel built for long voyages between suns",
  "rocket": "Fire below, aimed straight up and out",
  "void": "The vast empty dark between everything",
  "orbit": "The endless loop one body traces around another",
  "launch": "The tense countdown before everything lifts off",
  "spacewalk": "A tethered stroll outside the airlock",
  "alien": "A visitor from somewhere very far away",
  "exoplanet": "A distant world circling another sun",
  "eclipse": "When one bright thing hides behind another",
  "constellation": "Dots connected into a mythic picture overhead",
  "antimatter": "The mirror twin that annihilates on contact",
  "hyperspace": "The shortcut you jump into to skip the distance",
  "cryosleep": "The long frozen nap on a distant voyage",
  "terraforming": "Making a dead world breathable and green",
  "moonbase": "A quiet outpost on that pale grey neighbor",
  "colony": "A little settlement clinging to a new world",
  "spacecraft": "A crewed machine built to leave the ground",
  "shuttle": "A reusable ride ferrying up and back",
  "probe": "A tiny robot sent to look and report back",
  "solar": "Everything belonging to our home star",
  "lunar": "Tied to that pale monthly-changing orb",
  "stellar": "Belonging to those distant burning points",
  "cosmic": "On the grandest scale of all existence",
  "astral": "Dreamy, star-touched, beyond the physical body",
  "celestial": "Anything belonging to the heavens above",
  "interstellar": "The daunting gulf spanning between the suns",
  "zero gravity": "Where everything just floats, weightless and loose",
  "blackhole": "A pit so hungry not even light escapes",
  "Bigfoot": "Hairy giant leaving oversized prints in forests",
  "Mothman": "Winged red-eyed omen before disaster strikes",
  "Chupacabra": "Livestock predator of Latin American ranch tales",
  "Slenderman": "Faceless tall figure lurking in internet nightmares",
  "wendigo": "Starving winter spirit driven to eat flesh",
  "banshee": "Her wail foretells a death in Irish lore",
  "poltergeist": "The one that throws dishes around your house",
  "skinwalker": "Navajo shapeshifter you should not name aloud",
  "cryptid": "Unproven creature the believers keep chasing",
  "phantom": "A pale figure that fades through the walls",
  "specter": "A dim shape haunting the edge of sight",
  "apparition": "A sudden ghostly vision that vanishes fast",
  "haunting": "When a place refuses to let its dead rest",
  "possession": "When something else takes the driver's seat inside you",
  "curse": "Bad luck someone deliberately wished upon you",
  "hex": "A witch's little spell to sour your day",
  "omen": "A sign that something bad is coming",
  "ritual": "Candles and chanting for a spooky purpose",
  "séance": "Gathering around a table to call the dead",
  "ouija": "A planchette sliding toward letters at midnight",
  "cemetery": "Rows of stones where the dead are visited",
  "graveyard": "Church-yard plots beneath crooked old headstones",
  "tombstone": "The engraved slab marking who lies below",
  "crypt": "A stone chamber underground for the departed",
  "mausoleum": "A grand aboveground tomb for the wealthy dead",
  "coffin": "The long wooden box you get buried in",
  "ghost": "A see-through visitor from the other side",
  "spirit": "An unseen essence lingering after the body's gone",
  "shadow": "A dark figure glimpsed where none should be",
  "entity": "A vague presence too undefined to name",
  "demon": "An infernal being tormenting from below",
  "vampire": "Fanged night-dweller with a taste for blood",
  "werewolf": "Man who changes shape under the full moon",
  "zombie": "Shambling reanimated corpse craving brains",
  "ghoul": "A grave-dweller feasting on the buried dead",
  "monster": "A frightening thing that gives you nightmares",
  "creature": "An odd living thing lurking in the dark",
  "beast": "A savage animal thing, fierce and untamed",
  "legend": "A tale passed down, half true at best",
  "myth": "An ancient made-up story explaining the world",
  "folklore": "The old stories a whole culture keeps telling",
  "espresso": "A tiny cup with a big kick",
  "cappuccino": "Equal thirds crowned in an airy cloud",
  "latte": "Mostly milk with a coffee whisper",
  "macchiato": "Just a stain marks the milk",
  "americano": "A shot stretched out with hot water",
  "mocha": "Where the cocoa flirts with the roast",
  "frappe": "Blended, chilled, and topped for sipping",
  "cortado": "A small glass, milk cutting the edge",
  "affogato": "A scoop drowned by something hot",
  "ristretto": "Shorter and bolder than the usual pull",
  "barista": "The one wielding the machine behind the counter",
  "brew": "The act of coaxing flavor from grounds",
  "roast": "How dark the beans went in the oven",
  "beans": "Little kernels before the whole ritual begins",
  "grind": "Turning solids into gritty powder",
  "steam": "Hot vapor hissing to heat the milk",
  "foam": "The frothy pillow riding on top",
  "crema": "The golden layer atop a fresh pull",
  "drip": "Slow gravity through a paper cone",
  "pour": "A deliberate stream, often a fancy leaf",
  "French press": "Push the plunger down through the grounds",
  "AeroPress": "A plastic gadget you press by hand",
  "siphon": "Vacuum theater with bubbling glass chambers",
  "Turkish": "Unfiltered, fine grounds settling in the cup",
  "Vietnamese": "Sweet condensed richness dripping slow",
  "Irish": "A warming pour with a boozy secret",
  "iced": "Poured over cubes for a chilly sip",
  "cold brew": "Steeped long and slow, never heated",
  "nitro": "Cascading bubbles like a dark stout",
  "oat milk": "The trendy grain-based dairy dodge",
  "almond milk": "A nutty dairy-free swap",
  "soy milk": "The original bean-based dairy stand-in",
  "vanilla": "A pale sweet pod flavor everyone loves",
  "caramel": "Golden melted sweetness drizzled on top",
  "hazelnut": "A toasty nutty flavor shot",
  "cinnamon": "A warm spice dusted from a stick",
  "chocolate": "The cocoa side of the sweet aisle",
  "whipped cream": "An airy soft cloud squirted on top",
  "sprinkles": "Tiny colorful bits scattered for fun",
  "syrup": "The sticky sweet pump behind the counter",
  "sugar": "The plain white sweetener in a packet",
  "parkour": "Turning city walls into a playground",
  "skydiving": "Leaping where the ground is far below",
  "snowboarding": "One plank down a white mountain",
  "skateboarding": "Four wheels and a wooden deck",
  "surfing": "Standing tall on a rolling swell",
  "wakeboarding": "Towed across the lake behind an engine",
  "BMX": "Small bikes built for big air",
  "motocross": "Engines roaring across a dirt track",
  "kayaking": "One paddler slicing through the current",
  "rafting": "A team paddling down angry rapids",
  "climbing": "Fingertips against a vertical face",
  "bungee": "A cord snaps you back from the edge",
  "wingsuit": "Human flight in a fabric membrane",
  "paragliding": "Drifting under a soft fabric wing",
  "kitesurfing": "Wind, water, and a giant sail",
  "slacklining": "Balancing on a tightrope with slack",
  "highlining": "That same thin line, terrifyingly high",
  "drifting": "Steering sideways through a smoking corner",
  "rally": "Racing flat out on dirt roads",
  "downhill": "The fastest way to the bottom",
  "freeride": "Untamed terrain, no rules, no course",
  "halfpipe": "A curved snowy trench for tricks",
  "ramp": "An incline that launches you upward",
  "ollie": "Popping the board off the ground",
  "kickflip": "Spinning the board under your feet",
  "backflip": "Rotating heels over head in reverse",
  "frontflip": "Tumbling forward, head leading the way",
  "aerial": "A move performed entirely mid-flight",
  "trick": "A flashy move to impress the crowd",
  "stunt": "A daring feat that risks it all",
  "jump": "Leaving the earth for a moment",
  "drop": "Committing to a steep sudden descent",
  "carve": "Cutting smooth arcs into the terrain",
  "shred": "Attacking the slope with fierce style",
  "gnarly": "Describes something intense and a little dangerous",
  "radical": "An old-school word for seriously impressive",
  "tube": "The hollow curl a rider hides inside",
  "barrel": "That same curling wave, spinning around you",
  "wave": "A crest the surfers wait for",
  "powder": "Fresh untouched fluff on the mountain",
  "tarot": "A deck read to foretell your fate",
  "runes": "Old carved marks pulled for guidance",
  "pendulum": "It swings to answer yes or no",
  "dreamcatcher": "Woven web hung above your sleep",
  "cauldron": "Bubbling pot for a witch's brew",
  "grimoire": "A dusty book of spellcraft secrets",
  "athame": "A blade for the circle, never for cutting",
  "chalice": "A ceremonial goblet raised in rite",
  "pentacle": "Five points inside a protective circle",
  "orb": "A gazing sphere clouded with the future",
  "talisman": "A lucky object charged with purpose",
  "charm": "Small trinket believed to bend fortune",
  "scroll": "Ancient rolled parchment of forgotten lore",
  "tome": "A weighty volume of arcane knowledge",
  "elixir": "A tonic promising life or cure",
  "incense": "Fragrant smoke curling from a lit stick",
  "sage": "Bundled herb burned to cleanse a room",
  "smudge": "The wafting ritual to clear bad energy",
  "candle": "A lit flame set for intention",
  "altar": "The sacred table where offerings are laid",
  "offering": "A small gift left for the spirits",
  "divination": "The art of glimpsing hidden fates",
  "scrying": "Staring deep to see distant things",
  "mirror": "A reflective surface for peering beyond",
  "geode": "A plain rock hiding sparkle inside",
  "quartz": "Common clear stone said to amplify",
  "amethyst": "A calming purple gem for the crown",
  "obsidian": "Glassy black stone born of fire",
  "moonstone": "A milky shimmer tied to lunar cycles",
  "selenite": "A pale glowing wand of soft stone",
  "jade": "A smooth green stone prized for luck",
  "turquoise": "Sky-blue stone banded with earthy veins",
  "opal": "A stone flickering with hidden rainbows",
  "ruby": "A deep red gem of passion and fire",
  "cyberpunk": "High tech, low life, neon rain",
  "neon": "Buzzing tubes that paint the night",
  "hologram": "Light pretending to be solid",
  "implant": "Tech tucked beneath your skin",
  "cyborg": "Half flesh, half wired machine",
  "android": "Built to pass as one of us",
  "robot": "Metal worker that never tires",
  "drone": "Buzzing eye that hovers overhead",
  "AI": "The thinking that isn't human",
  "surveillance": "Always watched, never quite alone",
  "corporation": "The faceless power above the state",
  "wasteland": "Nothing grows out here anymore",
  "bunker": "Buried shelter for the worst day",
  "vault": "Sealed haven deep below ground",
  "radiation": "Invisible glow that makes you sick",
  "mutant": "Twisted by what poisoned the world",
  "clone": "A copy walking around as you",
  "synthetic": "Made in a lab, not nature",
  "virtual": "Real enough, but not quite there",
  "matrix": "The simulation you can't see out of",
  "grid": "The web of power lines humming",
  "network": "Everything wired to everything else",
  "firewall": "The barrier keeping intruders out",
  "hack": "Slipping past locks you shouldn't",
  "virus": "Tiny code that spreads and ruins",
  "malware": "Nasty software with bad intentions",
  "crash": "When it all suddenly stops working",
  "reboot": "Turn it off then on again",
  "upgrade": "The newer, shinier version arrives",
  "augment": "Boosting the body past its limits",
  "biometric": "Your fingerprint is the password",
  "scanner": "Sweeps a beam to read you",
  "chip": "Tiny wafer that runs the tech",
  "code": "Lines of instructions the machine reads",
  "data": "The raw stuff that gets stored",
  "upload": "Sending it up to the cloud",
  "download": "Pulling it down to your device",
  "server": "The big machine everyone connects to",
  "blanket": "Pull it up to your chin at night",
  "pillow": "Where your head lands after a long day",
  "hoodie": "Casual armor with a pouch up front",
  "slippers": "Quiet shuffling around the kitchen floor",
  "robe": "What you wear tying the sash loosely",
  "coffee": "The reason mornings become bearable at all",
  "cookies": "Best warm and straight off the tray",
  "soup": "Ladled into a bowl on cold days",
  "fireplace": "Crackling glow you gather around in winter",
  "hammock": "Strung between two trees for lazy swaying",
  "swing": "Back and forth, feet leaving the ground",
  "nap": "A short escape in the afternoon",
  "cuddle": "Two people tangled close on the couch",
  "snuggle": "Burrowing into warmth beside someone you like",
  "cozy": "That whole small-and-safe indoor feeling",
  "warm": "The opposite of a shivering chill",
  "soft": "What you want your pillow to be",
  "fuzzy": "Texture that tickles under your fingertips",
  "plush": "Overstuffed and squishable in the best way",
  "teddy": "A stuffed friend kids hug to sleep",
  "book": "Pages you turn curled up in a chair",
  "movie": "Popcorn and the couch on a quiet night",
  "music": "Melodies that set the whole room's mood",
  "rain": "That gentle patter against the window pane",
  "snow": "Silent white blanketing everything outside",
  "autumn": "Crisp air and leaves turning colors",
  "sweater": "Knitted layer for chilly indoor evenings",
  "scarf": "Wrapped around your neck against the wind",
  "mittens": "Keeps little hands toasty in the cold",
  "socks": "Slipped on to keep your feet warm",
  "pajamas": "What you change into before bed",
  "bath": "A long warm soak to unwind",
  "bubble": "Fragile little sphere floating in the tub",
  "aromatherapy": "Scents chosen to calm your frazzled nerves",
  "lavender": "That purple scent said to help sleep",
  "nostalgia": "That bittersweet ache for the good old days",
  "kraken": "A sailor's nightmare with too many arms",
  "megalodon": "Prehistoric jaws that dwarf today's hunters",
  "leviathan": "Something biblically huge lurking below",
  "serpent": "A long coiling shape in the swell",
  "siren": "Her song lures ships to doom",
  "shipwreck": "What the storm left on the seafloor",
  "treasure": "X marks a very shiny spot",
  "atlantis": "A city that supposedly sank away",
  "abyss": "So deep the light gives up",
  "trench": "The lowest scar on the planet",
  "reef": "A colorful maze fish call home",
  "kelp": "A swaying underwater forest of green",
  "jellyfish": "Drifting, translucent, and best not touched",
  "squid": "Ten arms and a jet of ink",
  "octopus": "Eight-limbed genius squeezing through cracks",
  "anglerfish": "It fishes with its own glowing bait",
  "shark": "A fin that clears the beach fast",
  "whale": "The biggest breath in the sea",
  "dolphin": "The clever grinning acrobat of the bay",
  "narwhal": "The one with a spiraled tusk",
  "seahorse": "Tiny rider where the dad gives birth",
  "starfish": "Five arms clinging to a tidepool rock",
  "coral": "Living stone building a rainbow city",
  "pearl": "A gem grown quietly inside a shell",
  "shell": "An empty spiral you hold to your ear",
  "tsunami": "A wall of water racing to shore",
  "whirlpool": "A spinning drain in the open sea",
  "maelstrom": "A monstrous spiral swallowing whole ships",
  "tide": "The moon's twice-daily pull on shore",
  "current": "An invisible river within the ocean",
  "depth": "How far down the darkness goes",
  "submarine": "It dives and hides beneath the surface",
  "anchor": "Heavy iron that keeps you put",
  "lighthouse": "A lonely beam warning ships off rocks",
  "buoy": "A bobbing marker on the swell",
  "sailor": "One who lives by the ship's ropes",
  "pirate": "He'd rather steal than sail honest",
  "mariner": "An old salt bound to the sea",
  "grandmacore": "Doilies, hard candies, and grandma's soft world",
  "bookshelf": "Where spines line up waiting to be read",
  "teacup": "Tiny handle, pinky optional, steam rising",
  "vintage": "Charmingly of another decade, not quite ancient",
  "antique": "Older than vintage, and it knows it",
  "rustic": "Rough around the edges, on purpose",
  "farmhouse": "Big kitchen table, barn just outside",
  "cottage": "A snug little dwelling with a garden",
  "cabin": "Wooden retreat where the woods start",
  "hearth": "Where the fire keeps the room warm",
  "quilt": "Patchwork warmth stitched from many squares",
  "knitting": "Two pointy sticks and a cozy loop",
  "crochet": "One hook loops yarn into soft shapes",
  "embroidery": "Needle and thread painting on fabric",
  "lace": "Delicate holes arranged into something pretty",
  "floral": "A pattern blooming across the fabric",
  "botanical": "Leafy illustrations from a plant lover's notebook",
  "garden": "A tended patch where green things grow",
  "greenhouse": "Glass walls keeping the growing things warm",
  "windowsill": "That sunny ledge where small pots sit",
  "plants": "Green companions that quietly need watering",
  "herbs": "Fragrant leaves for the pot and cures",
  "wildflower": "Untamed bloom nobody had to plant",
  "daisy": "White petals circling a cheerful yellow eye",
  "rose": "Beautiful, romantic, but watch the thorns",
  "honeysuckle": "Sweet climbing vine the bees adore",
  "mushroom": "Little forest cap that pops up overnight",
  "moss": "Soft green carpet on the damp stones",
  "fern": "Feathery fronds unfurling in the shade",
  "basket": "A woven hold-all for gathering things",
  "wicker": "That woven material chairs are made from",
  "pottery": "Shaped from mud, spun on a wheel",
  "ceramic": "Fired clay turned into your favorite mug",
  "handmade": "Crafted by human hands, flaws and all",
  "homemade": "Made in the kitchen, not a factory",
  "baking": "Warm oven, flour dusting, sweet smells",
  "bread": "A risen loaf pulled warm from the oven",
  "jam": "Sweet fruit trapped in a jar",
  "honey": "Golden sweetness straight from the hive",
  "Bollywood": "Song, dance, and heartbreak on a big screen",
  "chai": "A steaming cup spiced for the morning",
  "dosa": "Crispy and golden, folded from the south",
  "biryani": "Fragrant layers steamed for a feast",
  "samosa": "A crunchy triangle for teatime snacking",
  "naan": "Pillowy and blistered from a hot oven",
  "paneer": "Soft cubes soaking up a rich gravy",
  "curry": "A simmered, spiced bowl of comfort",
  "tandoor": "A blazing clay pit that chars everything",
  "masala": "A fragrant blend that wakes up a dish",
  "tikka": "Marinated bites charred on a skewer",
  "kebab": "Smoky morsels grilled over open flame",
  "lassi": "A cool, frothy sip for hot afternoons",
  "gulab jamun": "Soft syrupy spheres for a sweet ending",
  "jalebi": "Bright orange coils dripping with syrup",
  "kulfi": "A frozen treat on a stick, denser than most",
  "diwali": "Rows of little flames light the night",
  "holi": "Powder clouds and drenched, laughing crowds",
  "rangoli": "Colorful patterns drawn on the doorstep",
  "mehndi": "Delicate reddish designs painted on hands",
  "saree": "Yards of fabric draped for celebration",
  "kurta": "A loose long tunic for festive days",
  "dhoti": "A single cloth wrapped around the legs",
  "bindi": "A small dot worn between the brows",
  "tabla": "A pair of drums tapped by nimble fingers",
  "sitar": "Long-necked strings that bend and shimmer",
  "harmonium": "A hand-pumped box of reedy notes",
  "dhol": "A big barrel drum slung for celebration",
  "bhangra": "High-energy stomping from the northern fields",
  "kathak": "Spinning footwork telling an old story",
  "namaste": "Palms pressed together in polite greeting",
  "yoga": "Breath and postures for calm and balance",
  "mandir": "A carved place to leave your shoes outside",
  "taj mahal": "A white marble monument to lost love",
  "rickshaw": "Three wheels weaving through crowded streets",
  "bazaar": "A maze of stalls haggling over everything",
  "monsoon": "Months of downpour the whole land waits for",
  "cricket": "Bat, ball, and long afternoons on a pitch",
  "maharaja": "An old ruler dripping in jewels and palaces",
  "rajput": "A proud warrior clan of the desert forts",
  "hindi": "The most-spoken tongue of the northern plains",
  "punjabi": "A lively language from the land of five rivers",
  "bengali": "A poetic eastern tongue of rivers and sweets",
  "tamil": "An ancient southern language of great age"
}

// Look up the subtle impostor hint for a given word.
// Falls back to an empty string if a word somehow has no authored hint.
export function getHintForWord(word: string): string {
  return WORD_HINTS[word] ?? ''
}

// Seeded RNG helpers
function cyrb128(str: string): number[] {
  let h1 = 1779033703, h2 = 3144134277, h3 = 1013904242, h4 = 2773480762
  for (let i = 0, k; i < str.length; i++) {
    k = str.charCodeAt(i)
    h1 = h2 ^ Math.imul(h1 ^ k, 597399067)
    h2 = h3 ^ Math.imul(h2 ^ k, 2869860233)
    h3 = h4 ^ Math.imul(h3 ^ k, 951274213)
    h4 = h1 ^ Math.imul(h4 ^ k, 2716044179)
  }
  h1 = Math.imul(h3 ^ (h1 >>> 18), 597399067)
  h2 = Math.imul(h4 ^ (h2 >>> 22), 2869860233)
  h3 = Math.imul(h1 ^ (h3 >>> 17), 951274213)
  h4 = Math.imul(h2 ^ (h4 >>> 19), 2716044179)
  return [(h1 ^ h2 ^ h3 ^ h4) >>> 0]
}

function mulberry32(a: number) {
  return function() {
    let t = (a += 0x6D2B79F5)
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

export function seededRandFromKey(key: string) {
  const [seed] = cyrb128(key)
  return mulberry32(seed)
}

export function numberFromRng(rng: () => number, max: number): number {
  return Math.floor(rng() * max) % max
}

export function pickDeterministic<T>(rng: () => number, arr: T[]): T {
  return arr[Math.floor(rng() * arr.length) % arr.length]
}

export interface GameState {
  players: number
  round: number
  category: string
  activePlayer: number | null
  revealed: boolean
  impostorIndex: number
  chosenWord: string
  impostorHint: string
  startPlayerIndex: number
  gameStarted: boolean
}

export function createGameState(players: number, round: number, category: string): GameState {
  const roomKey = `${round}#${players}#${category}`

  // Handle "Random" category by picking a random category deterministically
  let actualCategory = category
  let words = WORD_BANK[category]

  if (category === 'Random') {
    const categoryRng = seededRandFromKey(roomKey + ':cat')
    actualCategory = pickDeterministic(categoryRng, ALL_CATEGORIES)
    words = WORD_BANK[actualCategory]
  }

  const impostorIndex = numberFromRng(seededRandFromKey(roomKey + ':imp'), players)
  const chosenWord = pickDeterministic(seededRandFromKey(roomKey + ':word'), words)
  const impostorHint = getHintForWord(chosenWord)
  const startPlayerIndex = numberFromRng(seededRandFromKey(roomKey + ':start'), players)

  return {
    players,
    round,
    category: actualCategory, // Store the actual category that was selected
    activePlayer: null,
    revealed: false,
    impostorIndex,
    chosenWord,
    impostorHint,
    startPlayerIndex,
    gameStarted: false
  }
}