// ---- Expanded word bank ----
export const WORD_BANK: Record<string, string[]> = {
  "Gen Z Vibes": [
    "rizz", "slay", "bussin", "delulu", "stan", "simp", "mid", "bestie", "purr",
    "sheesh", "unhinged", "gaslight", "gatekeep", "girlboss", "periodt", "respectfully",
    "situationship", "aesthetic", "vibe", "cringe", "basic", "salty", "shook", "sus",
    "tea", "flex", "clout", "fire", "lowkey", "highkey", "ghosting", "finsta",
    "FOMO", "GOAT", "lit", "savage", "shade", "thirsty", "woke", "yeet", "cap"
  ],
  "Psychedelic Trip": [
    "fractal", "kaleidoscope", "mandala", "chakra", "vibration", "enlightenment", "oneness",
    "transcendence", "portal", "spiral", "infinity", "cosmos", "dimension", "frequency",
    "energy", "aura", "crystal", "prism", "vortex", "nebula", "galaxy", "stardust",
    "moonbeam", "sunburst", "rainbow", "aurora", "mirage", "illusion", "vision", "dreamscape",
    "trance", "meditation", "nirvana", "bliss", "harmony", "unity", "consciousness", "awakening",
    "metamorphosis", "rebirth", "euphoria", "serenity"
  ],
  "Viral Internet": [
    "meme", "viral", "trending", "algorithm", "influencer", "aesthetic", "timeline", "multiverse",
    "speedrun", "cursed", "blessed", "chaotic", "cottagecore", "goblincore", "weirdcore",
    "traumacore", "vaporwave", "hyperpop", "girlhood", "boyhood", "adulting", "NPC",
    "main character", "side quest", "lore", "canon", "cringe", "based", "ratio", "stan",
    "simp", "touch grass", "chronically online", "unhinged", "feral", "goblin mode", "delulu",
    "rizz", "aura", "edgy", "softcore", "hardcore"
  ],
  "Fantasy Realms": [
    "dragon", "unicorn", "phoenix", "griffin", "basilisk", "chimera", "hydra", "pegasus", "centaur",
    "mermaid", "fairy", "elf", "dwarf", "goblin", "troll", "ogre", "orc", "wizard", "sorcerer",
    "witch", "warlock", "necromancer", "paladin", "ranger", "rogue", "bard", "druid", "monk",
    "wand", "staff", "amulet", "sword", "shield", "armor", "potion", "spell", "quest", "prophecy",
    "crystal", "dungeon", "castle"
  ],
  "Street Food": [
    "tacos", "churros", "empanadas", "samosas", "gyros", "shawarma", "kebabs", "takoyaki",
    "okonomiyaki", "elote", "arepas", "pupusas", "pho", "dumplings", "poutine", "roti",
    "crepes", "beignets", "falafel", "quesadilla", "burritos", "nachos", "pretzel", "corndog",
    "funnel cake", "waffle", "cronut", "donut", "bagel", "mochi", "bao", "tamale",
    "chimichanga", "tostada", "flautas", "gordita", "sope", "esquite", "chicharron", "churro", "bunuelo"
  ],
  "Retro Gaming": [
    "powerup", "checkpoint", "respawn", "fatality", "combo", "joystick", "controller",
    "cartridge", "pixel", "sprite", "noob", "pwned", "camping", "griefing", "loot",
    "boss", "health bar", "mana", "continue", "game over", "insert coin", "arcade",
    "highscore", "cheatcode", "speedrun", "glitch", "mod", "emulator", "ROM", "console",
    "platform", "sidescroller", "dungeon", "quest", "inventory", "save", "load", "pause", "warp", "secret", "bonus"
  ],
  "Space Odyssey": [
    "nebula", "quasar", "pulsar", "supernova", "wormhole", "asteroid", "comet", "meteor",
    "satellite", "starship", "rocket", "galaxy", "cosmos", "void", "orbit", "launch",
    "spacewalk", "alien", "exoplanet", "eclipse", "constellation", "antimatter", "hyperspace",
    "cryosleep", "terraforming", "moonbase", "colony", "spacecraft", "shuttle", "probe",
    "aurora", "solar", "lunar", "stellar", "cosmic", "astral", "celestial", "interstellar", "zero gravity", "stardust", "blackhole"
  ],
  "Urban Legends": [
    "Bigfoot", "Mothman", "Chupacabra", "Slenderman", "wendigo", "banshee", "poltergeist",
    "skinwalker", "cryptid", "phantom", "specter", "apparition", "haunting", "possession",
    "curse", "hex", "omen", "ritual", "séance", "ouija", "cemetery", "graveyard",
    "tombstone", "crypt", "mausoleum", "coffin", "ghost", "spirit", "shadow", "entity",
    "demon", "vampire", "werewolf", "zombie", "ghoul", "monster", "creature", "beast", "legend", "myth", "folklore"
  ],
  "Coffee Culture": [
    "espresso", "cappuccino", "latte", "macchiato", "americano", "mocha", "frappe",
    "cortado", "affogato", "ristretto", "barista", "brew", "roast", "beans", "grind",
    "steam", "foam", "crema", "drip", "pour", "French press", "AeroPress", "siphon",
    "Turkish", "Vietnamese", "Irish", "iced", "cold brew", "nitro", "oat milk", "almond milk",
    "soy milk", "vanilla", "caramel", "hazelnut", "cinnamon", "chocolate", "whipped cream", "sprinkles", "syrup", "sugar"
  ],
  "Extreme Sports": [
    "parkour", "skydiving", "snowboarding", "skateboarding", "surfing", "wakeboarding",
    "BMX", "motocross", "kayaking", "rafting", "climbing", "bungee", "wingsuit",
    "paragliding", "kitesurfing", "slacklining", "highlining", "drifting", "rally",
    "downhill", "freeride", "halfpipe", "ramp", "grind", "ollie", "kickflip", "backflip",
    "frontflip", "aerial", "trick", "stunt", "jump", "drop", "carve", "shred", "gnarly",
    "radical", "tube", "barrel", "wave", "powder"
  ],
  "Mystical Artifacts": [
    "crystal", "tarot", "runes", "pendulum", "dreamcatcher", "cauldron", "grimoire",
    "athame", "chalice", "pentacle", "wand", "orb", "amulet", "talisman", "charm",
    "scroll", "tome", "spell", "potion", "elixir", "incense", "sage", "smudge",
    "candle", "altar", "offering", "ritual", "divination", "scrying", "mirror",
    "geode", "quartz", "amethyst", "obsidian", "moonstone", "selenite", "jade", "turquoise", "opal", "ruby"
  ],
  "Dystopian Future": [
    "cyberpunk", "neon", "hologram", "implant", "cyborg", "android", "robot", "drone",
    "AI", "algorithm", "surveillance", "corporation", "wasteland", "bunker", "vault",
    "radiation", "mutant", "clone", "synthetic", "virtual", "matrix", "grid", "network",
    "firewall", "hack", "virus", "malware", "glitch", "crash", "reboot", "upgrade",
    "augment", "biometric", "scanner", "chip", "code", "data", "upload", "download", "server"
  ],
  "Comfort Things": [
    "blanket", "pillow", "hoodie", "slippers", "robe", "candle", "tea", "coffee",
    "chocolate", "cookies", "soup", "fireplace", "hammock", "swing", "nap", "cuddle",
    "snuggle", "cozy", "warm", "soft", "fuzzy", "plush", "teddy", "book", "movie",
    "music", "rain", "snow", "autumn", "sweater", "scarf", "mittens", "socks", "pajamas",
    "bath", "bubble", "aromatherapy", "lavender", "vanilla", "cinnamon", "nostalgia"
  ],
  "Ocean Mysteries": [
    "kraken", "megalodon", "leviathan", "serpent", "mermaid", "siren", "shipwreck",
    "treasure", "atlantis", "abyss", "trench", "reef", "kelp", "jellyfish", "squid",
    "octopus", "anglerfish", "shark", "whale", "dolphin", "narwhal", "seahorse", "starfish",
    "coral", "pearl", "shell", "tsunami", "whirlpool", "maelstrom", "tide", "current",
    "wave", "depth", "submarine", "anchor", "lighthouse", "buoy", "sailor", "pirate", "mariner"
  ],
  "Cozy Aesthetics": [
    "cottagecore", "grandmacore", "bookshelf", "teacup", "vintage", "antique", "rustic",
    "farmhouse", "cottage", "cabin", "hearth", "quilt", "knitting", "crochet", "embroidery",
    "lace", "floral", "botanical", "garden", "greenhouse", "windowsill", "plants", "herbs",
    "wildflower", "daisy", "rose", "lavender", "honeysuckle", "mushroom", "moss", "fern",
    "basket", "wicker", "pottery", "ceramic", "handmade", "homemade", "baking", "bread", "jam", "honey"
  ],
  "Indian": [
    "Bollywood", "chai", "dosa", "biryani", "samosa", "naan", "paneer", "curry",
    "tandoor", "masala", "tikka", "kebab", "lassi", "gulab jamun", "jalebi", "kulfi",
    "diwali", "holi", "rangoli", "mehndi", "saree", "kurta", "dhoti", "bindi",
    "tabla", "sitar", "harmonium", "dhol", "bhangra", "kathak", "namaste", "yoga",
    "mandir", "taj mahal", "rickshaw", "bazaar", "monsoon", "cricket", "maharaja", "rajput",
    "hindi", "punjabi", "bengali", "tamil"
  ]
}

export const ALL_CATEGORIES = Object.keys(WORD_BANK)

// ---- Impostor hints ----
// One subtle, hand-authored clue per word. Deliberately vague — it should give
// the impostor a general sense of the vibe to bluff the first round, while
// several words in the category could plausibly fit, so it never reveals the answer.
export const WORD_HINTS: Record<string, string> = {
  "rizz": "A bit of social magic",
  "slay": "High praise, delivered loudly",
  "bussin": "When something just hits right",
  "delulu": "Living in your own head",
  "stan": "Fandom taken very seriously",
  "simp": "Trying a little too hard",
  "mid": "A gentle little insult",
  "bestie": "Warm terms of endearment",
  "purr": "A satisfied little sound",
  "sheesh": "An outburst of pure reaction",
  "unhinged": "Pleasantly out of control",
  "gaslight": "A murky mind-game energy",
  "gatekeep": "Guarding what you love",
  "girlboss": "An empowerment-flavored buzzword",
  "periodt": "End of discussion, basically",
  "respectfully": "Softening something before you say it",
  "situationship": "Modern romance, undefined",
  "aesthetic": "A curated online mood",
  "vibe": "An unspoken feeling in the air",
  "cringe": "Secondhand embarrassment territory",
  "basic": "A mildly dismissive label",
  "salty": "A sour little mood",
  "shook": "Caught totally off guard",
  "sus": "Something feels a bit off",
  "tea": "Juicy little details",
  "flex": "A show-offy energy",
  "clout": "Chasing online status",
  "fire": "Enthusiastic approval",
  "lowkey": "Quietly, sort of admitting it",
  "highkey": "Openly, no shame about it",
  "ghosting": "A modern dating headache",
  "finsta": "A private online alter ego",
  "FOMO": "Anxious about missing out",
  "GOAT": "The very highest praise",
  "lit": "Peak party energy",
  "savage": "Bold and unbothered",
  "shade": "A subtle little dig",
  "thirsty": "Wanting attention a bit much",
  "woke": "Socially switched-on",
  "yeet": "A burst of chaotic energy",
  "cap": "Something not quite true",
  "fractal": "Patterns that keep unfolding",
  "kaleidoscope": "Shifting colors and shapes",
  "mandala": "Something intricate and sacred",
  "chakra": "Inner energy stuff",
  "vibration": "A subtle inner buzz",
  "enlightenment": "Reaching a higher state",
  "oneness": "Feeling connected to everything",
  "transcendence": "Rising beyond the ordinary",
  "portal": "A doorway to elsewhere",
  "spiral": "Turning inward and around",
  "infinity": "Something that never ends",
  "cosmos": "Gazing at the vast beyond",
  "dimension": "Another layer of reality",
  "frequency": "An unseen wavelength",
  "energy": "An invisible force flowing",
  "aura": "An unseen glow around you",
  "crystal": "Something clear and precious",
  "prism": "Splitting the light",
  "vortex": "Getting pulled in and around",
  "nebula": "Something vast and glowing far off",
  "galaxy": "The great expanse above",
  "stardust": "Cosmic bits drifting",
  "moonbeam": "Soft light in the night",
  "sunburst": "A flood of bright warmth",
  "rainbow": "A spread of colors",
  "aurora": "Lights dancing in the sky",
  "mirage": "Something not quite real",
  "illusion": "Your eyes playing tricks",
  "vision": "Something seen in the mind",
  "dreamscape": "A landscape of the mind",
  "trance": "Slipping into a dazed state",
  "meditation": "A quiet inward practice",
  "nirvana": "The ultimate peaceful state",
  "bliss": "Pure floating joy",
  "harmony": "Everything in balance",
  "unity": "All coming together as one",
  "consciousness": "The stuff of awareness",
  "awakening": "Coming into new clarity",
  "metamorphosis": "A deep change within",
  "rebirth": "Beginning anew",
  "euphoria": "An overwhelming high",
  "serenity": "Deep calm settling in",
  "meme": "A joke that spreads itself",
  "viral": "Suddenly everyone has seen it",
  "trending": "Riding the current wave",
  "algorithm": "The unseen hand behind your feed",
  "influencer": "Someone the internet follows",
  "timeline": "Your endless scroll of updates",
  "multiverse": "Endless what-if versions of things",
  "speedrun": "Racing to the finish",
  "cursed": "Something feels a little off",
  "blessed": "A wholesome little pick-me-up",
  "chaotic": "Everything's a mess and that's fine",
  "cottagecore": "A soft romanticized daydream",
  "goblincore": "Embracing the messy and offbeat",
  "weirdcore": "Something unsettling yet familiar",
  "traumacore": "Heavy feelings dressed up online",
  "vaporwave": "A hazy retro mood",
  "hyperpop": "Loud, overstimulated internet energy",
  "girlhood": "A season of growing up",
  "boyhood": "A season of growing up",
  "adulting": "The grind of grown-up life",
  "NPC": "Just going through the motions",
  "main character": "Living like the world watches",
  "side quest": "A little detour from the plan",
  "lore": "The backstory nobody explains",
  "canon": "What officially counts",
  "based": "Boldly unbothered by opinions",
  "ratio": "An online popularity contest",
  "touch grass": "Maybe step outside for once",
  "chronically online": "Too deep in the feed",
  "feral": "Wild and unrestrained energy",
  "goblin mode": "Gleefully giving up on yourself",
  "edgy": "Trying to seem a little dangerous",
  "softcore": "Gentle and toned down",
  "hardcore": "Turned all the way up",
  "dragon": "A creature from old legends",
  "unicorn": "Something pure and rarely seen",
  "phoenix": "Rising from something ended",
  "griffin": "A noble beast of myth",
  "basilisk": "Something best not looked at",
  "chimera": "A stitched-together strangeness",
  "hydra": "A menace that keeps returning",
  "pegasus": "A graceful thing from fables",
  "centaur": "Half of something wild",
  "mermaid": "A tale from the water",
  "fairy": "A small bit of magic",
  "elf": "Old woodland folklore",
  "dwarf": "Folk of the deep places",
  "goblin": "A mischievous little menace",
  "troll": "Something lurking off the path",
  "ogre": "A big and brutish tale",
  "orc": "A foe from dark armies",
  "wizard": "A wielder of the arcane",
  "sorcerer": "Someone touched by power",
  "witch": "A whisper of old magic",
  "warlock": "A darker sort of magic",
  "necromancer": "Meddling with forbidden things",
  "paladin": "A sworn and righteous figure",
  "ranger": "A wanderer of the wilds",
  "rogue": "Someone who works in shadow",
  "bard": "A teller of tales",
  "druid": "Bound to the natural world",
  "monk": "A life of quiet discipline",
  "wand": "A tool of the mystic",
  "staff": "An old traveler's companion",
  "amulet": "A charm worth keeping close",
  "sword": "The stuff of heroic tales",
  "shield": "Something to stand behind",
  "armor": "Protection for the bold",
  "potion": "A brew with hidden effects",
  "spell": "A touch of the arcane",
  "quest": "A long and fabled journey",
  "prophecy": "Words about what's to come",
  "dungeon": "A place best escaped",
  "castle": "A grand old stronghold",
  "tacos": "A messy handheld street bite",
  "churros": "A sweet treat from the fair",
  "empanadas": "A little pocket of comfort",
  "samosas": "A crispy snack with a kick",
  "gyros": "Street food off a spinning stack",
  "shawarma": "Carved fresh at a busy stand",
  "kebabs": "Sizzling bites from an open flame",
  "takoyaki": "A hot little bite from the cart",
  "okonomiyaki": "Griddle food, savory and loaded",
  "elote": "A warm snack on a stick",
  "arepas": "Simple street fare, humble and filling",
  "pupusas": "A stuffed griddle staple",
  "pho": "A steaming bowl to slurp",
  "dumplings": "Little bundles, steamy and satisfying",
  "poutine": "Messy comfort food, best when cold out",
  "roti": "A soft staple, torn and shared",
  "crepes": "Something thin folded around a treat",
  "beignets": "A pillowy sweet from the stand",
  "falafel": "A crispy handful, herby and green",
  "quesadilla": "Warm, cheesy, off the griddle",
  "burritos": "A hefty handheld, wrapped up tight",
  "nachos": "A shareable pile to snack on",
  "pretzel": "A knotty snack from the corner",
  "corndog": "Fried food on a stick",
  "funnel cake": "A sweet mess from the fairground",
  "waffle": "A griddled treat, crisp and golden",
  "cronut": "A trendy sweet from the bakery line",
  "donut": "A classic sweet ring of dough",
  "bagel": "A chewy round to grab and go",
  "mochi": "A soft chewy sweet bite",
  "bao": "A pillowy steamed pocket",
  "tamale": "Wrapped and steamed, unwrap to eat",
  "chimichanga": "A crispy hefty handheld",
  "tostada": "A crunchy loaded base",
  "flautas": "Crispy rolled and fried",
  "gordita": "A thick pocket, stuffed and warm",
  "sope": "A little masa base, loaded up",
  "esquite": "A warm cup of street snacking",
  "chicharron": "A crunchy fried indulgence",
  "churro": "A sweet fried fairground bite",
  "bunuelo": "A crisp fried sweet treat",
  "powerup": "A fleeting burst of luck",
  "checkpoint": "A place worth reaching",
  "respawn": "Something that happens mid-game",
  "fatality": "A brutal finish",
  "combo": "Things chained together",
  "joystick": "An old plaything in your hands",
  "controller": "Something you hold and grip",
  "cartridge": "A little relic of the past",
  "pixel": "The tiniest piece of a picture",
  "sprite": "A tiny animated thing",
  "noob": "Someone still figuring it out",
  "pwned": "A moment of pure humiliation",
  "camping": "A patient, sneaky tactic",
  "griefing": "Ruining someone else's fun",
  "loot": "A reward worth grabbing",
  "boss": "A looming challenge ahead",
  "health bar": "Something you keep an eye on",
  "mana": "An invisible resource running low",
  "continue": "Getting another shot at it",
  "game over": "When it all comes to an end",
  "insert coin": "A price of admission",
  "arcade": "A loud, glowing hangout",
  "highscore": "Something to brag about",
  "cheatcode": "A sneaky shortcut",
  "glitch": "When something goes weird",
  "mod": "A tweak to the usual thing",
  "emulator": "Pretending to be something else",
  "ROM": "A stored bit of the past",
  "console": "A box in the living room",
  "platform": "The ground beneath it all",
  "sidescroller": "Always moving along",
  "inventory": "A stash you carry around",
  "save": "Holding onto progress",
  "load": "Bringing something back",
  "pause": "A brief moment of stillness",
  "warp": "A quick way across",
  "secret": "Something hidden away",
  "bonus": "A little something extra",
  "quasar": "Something blazing in the distance",
  "pulsar": "A faint signal from afar",
  "supernova": "Something dramatic out in space",
  "wormhole": "A strange shortcut in physics",
  "asteroid": "Debris drifting through the dark",
  "comet": "A wanderer passing through",
  "meteor": "Something streaking through the sky",
  "satellite": "Quietly circling above us",
  "starship": "The stuff of space adventures",
  "rocket": "The thrill of going up",
  "void": "The great empty beyond",
  "orbit": "Going round and round out there",
  "launch": "A big countdown moment",
  "spacewalk": "An astronaut's bold outing",
  "alien": "Something not from here",
  "exoplanet": "A distant world out there",
  "eclipse": "A rare sky event",
  "constellation": "Shapes we trace at night",
  "antimatter": "Exotic physics, hard to grasp",
  "hyperspace": "A sci-fi way to travel fast",
  "cryosleep": "A long journey's strange rest",
  "terraforming": "Reshaping a distant world",
  "moonbase": "An outpost far from home",
  "colony": "Settling somewhere far away",
  "spacecraft": "A vessel for the great beyond",
  "shuttle": "A ride to and from up there",
  "probe": "Sent out to explore quietly",
  "solar": "Something about our bright star",
  "lunar": "Something about the night sky",
  "stellar": "Something to do with distant suns",
  "cosmic": "A vast, otherworldly vibe",
  "astral": "An ethereal, faraway feeling",
  "celestial": "Something heavenly and distant",
  "interstellar": "Spanning the vast dark between",
  "zero gravity": "A weightless, floating feeling",
  "blackhole": "Where the deep dark pulls",
  "Bigfoot": "Something people swear they saw",
  "Mothman": "A strange sighting people whisper about",
  "Chupacabra": "A menace blamed for missing livestock",
  "Slenderman": "Born from the modern internet's fears",
  "wendigo": "Hunger that haunts the cold wild",
  "banshee": "Something from spooky old stories",
  "poltergeist": "An unseen troublemaker in the house",
  "skinwalker": "Whispered tales best left alone",
  "cryptid": "Something science refuses to confirm",
  "phantom": "A presence you feel but can't touch",
  "specter": "A presence you sense but can't touch",
  "apparition": "A fleeting glimpse of the unreal",
  "haunting": "An unsettling lingering presence",
  "possession": "When something takes hold of you",
  "curse": "Misfortune that follows you around",
  "hex": "A little dark mischief cast your way",
  "omen": "A sign that something's coming",
  "ritual": "Something solemn and repeated",
  "séance": "Reaching toward the other side",
  "ouija": "A parlor game with eerie undertones",
  "cemetery": "A quiet place of final rest",
  "graveyard": "A quiet resting place for many",
  "tombstone": "Where names are set in stone",
  "crypt": "A cold place beneath the surface",
  "mausoleum": "A grand resting place for the dead",
  "coffin": "Where the departed are laid",
  "ghost": "A creature of the night's imagination",
  "spirit": "Something lingering beyond the living",
  "shadow": "Something that follows in the dark",
  "entity": "A vague presence with no name",
  "demon": "Something dark and otherworldly",
  "vampire": "A creature of the night",
  "werewolf": "A creature that changes with the moon",
  "zombie": "The dead that won't stay down",
  "ghoul": "Something that lurks near the dead",
  "monster": "Something that frightens in the dark",
  "creature": "Something not quite of this world",
  "beast": "Something wild and fearsome",
  "legend": "A story passed down through time",
  "myth": "An old story passed down",
  "folklore": "Old tales handed down for ages",
  "espresso": "A little cafe ritual",
  "cappuccino": "A cozy cafe order",
  "latte": "Something warm to sip",
  "macchiato": "A quiet cafe indulgence",
  "americano": "A familiar cafe order",
  "mocha": "Something sweet and warm",
  "frappe": "A chilled little treat",
  "cortado": "A small cafe pleasure",
  "affogato": "A cafe dessert of sorts",
  "ristretto": "A short cafe ritual",
  "barista": "The heart of the cafe",
  "brew": "The morning ritual",
  "roast": "Something warm in the air",
  "beans": "Where it all begins",
  "grind": "Part of the morning process",
  "steam": "A warm cafe wisp",
  "foam": "A soft finishing touch",
  "crema": "A subtle golden detail",
  "drip": "A slow morning ritual",
  "pour": "A gentle cafe motion",
  "French press": "An old-fashioned home ritual",
  "AeroPress": "A hands-on brewing gadget",
  "siphon": "A theatrical brewing method",
  "Turkish": "A far-off cafe tradition",
  "Vietnamese": "An exotic cafe custom",
  "Irish": "A warming grown-up treat",
  "iced": "A cool afternoon pick",
  "cold brew": "A chilled slow ritual",
  "nitro": "A modern chilled twist",
  "oat milk": "A trendy little addition",
  "almond milk": "A lighter little swap",
  "soy milk": "A familiar dairy-free swap",
  "vanilla": "A sweet familiar touch",
  "caramel": "A sweet golden touch",
  "hazelnut": "A cozy nutty note",
  "cinnamon": "A warm spiced whisper",
  "chocolate": "A sweet indulgent hint",
  "whipped cream": "A soft sweet topping",
  "sprinkles": "A playful finishing touch",
  "syrup": "A little something for flavor",
  "sugar": "A small sweet addition",
  "parkour": "City streets, but faster",
  "skydiving": "A serious adrenaline rush",
  "snowboarding": "Chasing the cold thrill",
  "skateboarding": "Concrete and attitude",
  "surfing": "Answering the ocean's call",
  "wakeboarding": "Pulled along the water",
  "BMX": "Two wheels, big energy",
  "motocross": "Loud, dusty, and fearless",
  "kayaking": "Moving with the current",
  "rafting": "A wet team adventure",
  "climbing": "Always looking up",
  "bungee": "A leap of faith",
  "wingsuit": "Flirting with the sky",
  "paragliding": "Drifting far above",
  "kitesurfing": "Wind meets water",
  "slacklining": "Balance is everything",
  "highlining": "Balance, way up high",
  "drifting": "All about control and speed",
  "rally": "A race against the terrain",
  "downhill": "Gravity does the work",
  "freeride": "No rules, just flow",
  "halfpipe": "Back and forth, up and over",
  "ramp": "Where the launch begins",
  "ollie": "The basics of style",
  "kickflip": "A move that earns respect",
  "backflip": "Turning the world upside down",
  "frontflip": "A dizzying show of nerve",
  "aerial": "A moment off the ground",
  "trick": "Something to show off",
  "stunt": "Bold and a little reckless",
  "jump": "Brief flight",
  "drop": "Committing to the plunge",
  "carve": "Cutting a clean line",
  "shred": "Going all out",
  "gnarly": "Words for the intense",
  "radical": "Slang with an edge",
  "tube": "Inside the moment",
  "barrel": "Where the wave curls",
  "wave": "The ocean's rhythm",
  "powder": "Fresh and untouched",
  "tarot": "A glimpse of what may come",
  "runes": "Old marks that carry meaning",
  "pendulum": "It answers if you ask",
  "dreamcatcher": "Something hung for peace of mind",
  "cauldron": "A tool of old magic",
  "grimoire": "Where secrets are kept written",
  "athame": "An instrument for solemn rites",
  "chalice": "Something raised in ceremony",
  "pentacle": "A sign with quiet power",
  "orb": "A round window into mystery",
  "talisman": "Carried to draw good fortune",
  "charm": "A little something for luck",
  "scroll": "Old wisdom rolled away",
  "tome": "Weighty pages of the arcane",
  "elixir": "A draught with promise",
  "incense": "It sweetens the sacred air",
  "sage": "Nature's touch in ritual",
  "smudge": "Clearing a space of shadows",
  "candle": "A small flame for focus",
  "altar": "Where the sacred is set",
  "offering": "Given to unseen powers",
  "divination": "Seeking to know the hidden",
  "scrying": "Peering toward the unknown",
  "mirror": "A surface that may reveal",
  "geode": "Earth's hidden little treasure",
  "quartz": "A stone said to hold power",
  "amethyst": "A pretty stone with meaning",
  "obsidian": "Born of fire and earth",
  "moonstone": "A stone touched by night",
  "selenite": "A pale stone of calm",
  "jade": "An old and treasured stone",
  "turquoise": "A stone of earth and sky",
  "opal": "A gem that plays with light",
  "ruby": "A prized and precious stone",
  "cyberpunk": "A jaded, rain-slick future",
  "neon": "A glow after dark",
  "hologram": "Not quite really there",
  "implant": "Something buried within",
  "cyborg": "Something part human, part not",
  "android": "Almost one of us",
  "robot": "Built to obey",
  "drone": "Something watching from above",
  "AI": "A mind not born",
  "surveillance": "Someone is always watching",
  "corporation": "Faceless power at the top",
  "wasteland": "What remains after the worst",
  "bunker": "A place to hide below",
  "vault": "Sealed away from the world",
  "radiation": "An invisible lingering threat",
  "mutant": "Changed into something else",
  "clone": "Made in another's image",
  "synthetic": "Not born of nature",
  "virtual": "Real, but not quite",
  "matrix": "A world beneath the world",
  "grid": "Everything wired together",
  "network": "Everything wired together, connected",
  "firewall": "Something from the digital world",
  "hack": "Getting in where you shouldn't",
  "virus": "Something that spreads and spoils",
  "malware": "A quiet digital menace",
  "crash": "When it all falls apart",
  "reboot": "Starting over from nothing",
  "upgrade": "Made a little better",
  "augment": "Pushed beyond the natural",
  "biometric": "Your body as a key",
  "scanner": "Reading what it sees",
  "chip": "A tiny thing inside",
  "code": "The language machines obey",
  "data": "Endless streams of it",
  "upload": "Sending it up and out",
  "download": "Pulling it in from afar",
  "server": "Where it all lives",
  "blanket": "Something warm you reach for",
  "pillow": "A soft bedtime comfort",
  "hoodie": "Easy comfort you can wear",
  "slippers": "Small home comforts for chilly moments",
  "robe": "Something soft to wrap up in",
  "coffee": "A warm morning comfort",
  "cookies": "A homey little treat",
  "soup": "Something warm and nourishing",
  "fireplace": "A cozy source of warmth",
  "hammock": "Somewhere to laze and unwind",
  "swing": "A gentle, easygoing pastime",
  "nap": "A little midday escape",
  "cuddle": "Closeness that feels safe",
  "snuggle": "Warmth shared up close",
  "cozy": "That snug, settled feeling",
  "warm": "A gentle, comforting glow",
  "soft": "Something gentle to the touch",
  "fuzzy": "A gentle, tender texture",
  "plush": "Something cushy and inviting",
  "teddy": "An old source of comfort",
  "book": "A quiet way to unwind",
  "movie": "A relaxed night-in treat",
  "music": "Something soothing in the background",
  "rain": "A mellow, cozy weather mood",
  "snow": "A calm, hushed winter mood",
  "autumn": "A cozy seasonal feeling",
  "sweater": "Cozy layers for cooler days",
  "scarf": "A snug bit of winter comfort",
  "mittens": "Small comforts against the cold",
  "socks": "Little warm everyday comforts",
  "pajamas": "Comfy things for winding down",
  "bath": "A warm, soothing soak",
  "bubble": "A playful bit of pampering",
  "aromatherapy": "A calming, scented indulgence",
  "lavender": "A soft, soothing scent",
  "nostalgia": "A warm feeling from the past",
  "kraken": "An old sailor's dread",
  "megalodon": "Something ancient the water swallowed",
  "leviathan": "A vast shape beneath the waves",
  "serpent": "Something coiling in dark water",
  "siren": "A lure from the open water",
  "shipwreck": "What the sea kept below",
  "treasure": "Something the depths still hide",
  "atlantis": "A story lost to the waves",
  "abyss": "Where the water goes dark",
  "trench": "Somewhere far below the surface",
  "reef": "A hidden place under the shallows",
  "kelp": "Something drifting in the shallows",
  "jellyfish": "A drifting thing in the blue",
  "squid": "Something from the darker depths",
  "octopus": "A shy dweller down below",
  "anglerfish": "A strange thing far below",
  "shark": "Something that keeps swimmers wary",
  "whale": "A giant of the open sea",
  "dolphin": "A familiar face at sea",
  "narwhal": "A creature of colder waters",
  "seahorse": "Something small in the shallows",
  "starfish": "A tiny thing near the shore",
  "coral": "A quiet thing beneath the surface",
  "pearl": "A small treasure from the sea",
  "shell": "Something washed up on sand",
  "tsunami": "When the sea turns violent",
  "whirlpool": "Where the water pulls you down",
  "maelstrom": "A churning danger at sea",
  "tide": "The sea's steady rhythm",
  "current": "An unseen pull in the water",
  "depth": "How far the water goes down",
  "submarine": "Something that travels below",
  "anchor": "Gear that keeps a ship in place",
  "lighthouse": "Something out by the coast",
  "buoy": "A marker on the water",
  "sailor": "Someone who works the sea",
  "pirate": "A rogue of the open water",
  "mariner": "Someone whose life is the sea",
  "grandmacore": "Warmth of a bygone home",
  "bookshelf": "A quiet corner of the home",
  "teacup": "A small comfort for slow mornings",
  "vintage": "Charm from another era",
  "antique": "Something with years behind it",
  "rustic": "Plain, simple, old-world charm",
  "farmhouse": "Simple country living",
  "cottage": "A snug little country place",
  "cabin": "A cozy retreat away from it all",
  "hearth": "The warm heart of a home",
  "quilt": "Something soft and comforting",
  "knitting": "A cozy handmade hobby",
  "crochet": "A patient handmade craft",
  "embroidery": "Careful work by hand",
  "lace": "A delicate old-fashioned touch",
  "floral": "A soft pretty pattern",
  "botanical": "Leafy and green in spirit",
  "garden": "Something tended outdoors",
  "greenhouse": "Where green things thrive",
  "windowsill": "A little sunlit spot indoors",
  "plants": "Living green things at home",
  "herbs": "Something fresh from the kitchen garden",
  "wildflower": "A little bloom growing free",
  "daisy": "Something from the garden",
  "rose": "A classic garden favorite",
  "honeysuckle": "Sweetness climbing in the garden",
  "mushroom": "Something that grows in the damp",
  "moss": "Soft and green underfoot",
  "fern": "A leafy shade-loving thing",
  "basket": "A humble little carryall",
  "wicker": "Handwoven and homey",
  "pottery": "Something shaped by hand",
  "ceramic": "Made from earth and fire",
  "handmade": "Crafted with care",
  "homemade": "Made lovingly at home",
  "baking": "A warm kitchen pastime",
  "bread": "Something warm from the oven",
  "jam": "A sweet homemade treat",
  "honey": "A golden little indulgence",
  "Bollywood": "India's dazzling entertainment world",
  "chai": "A warm everyday comfort",
  "dosa": "A popular Indian bite",
  "biryani": "A dish made for celebrations",
  "samosa": "A tasty little snack",
  "naan": "Something served with a meal",
  "paneer": "A common ingredient at dinner",
  "curry": "A flavorful home-cooked staple",
  "tandoor": "Where the cooking happens",
  "masala": "Adds richness to food",
  "tikka": "A savory Indian favorite",
  "kebab": "A hearty grilled bite",
  "lassi": "Something refreshing to sip",
  "gulab jamun": "A sweet festive treat",
  "jalebi": "A sugary indulgence",
  "kulfi": "A cool sweet delight",
  "diwali": "A joyful Indian occasion",
  "holi": "A vibrant seasonal celebration",
  "rangoli": "A decorative festive touch",
  "mehndi": "An adornment for special days",
  "saree": "Something worn on a special day",
  "kurta": "Everyday traditional attire",
  "dhoti": "A classic garment for men",
  "bindi": "A small traditional accent",
  "tabla": "An Indian musical thing",
  "sitar": "Heard in classical performance",
  "harmonium": "Part of a musical ensemble",
  "dhol": "Something that keeps the beat",
  "bhangra": "An energetic cultural expression",
  "kathak": "A graceful traditional art",
  "namaste": "A familiar Indian greeting",
  "yoga": "A calming mindful practice",
  "mandir": "A place of devotion",
  "taj mahal": "A famed Indian landmark",
  "rickshaw": "A way to get around town",
  "bazaar": "A bustling public spot",
  "monsoon": "A seasonal force of nature",
  "cricket": "A beloved national pastime",
  "maharaja": "Echoes of royal India",
  "rajput": "Rooted in warrior heritage",
  "hindi": "A regional tongue",
  "punjabi": "A regional tongue",
  "bengali": "A regional tongue",
  "tamil": "A regional tongue"
}

// Look up the subtle impostor hint for a given word.
// Falls back to an empty string if a word somehow has no authored hint.
export function getHintForWord(word: string): string {
  return WORD_HINTS[word] ?? ''
}

// Seeded RNG helpers
function cyrb128(str: string): number[] {
  let h1 = 1779033703, h2 = 3144134277, h3 = 1013904242, h4 = 2773480762
  for (let i = 0, k; i < str.length; i++) {
    k = str.charCodeAt(i)
    h1 = h2 ^ Math.imul(h1 ^ k, 597399067)
    h2 = h3 ^ Math.imul(h2 ^ k, 2869860233)
    h3 = h4 ^ Math.imul(h3 ^ k, 951274213)
    h4 = h1 ^ Math.imul(h4 ^ k, 2716044179)
  }
  h1 = Math.imul(h3 ^ (h1 >>> 18), 597399067)
  h2 = Math.imul(h4 ^ (h2 >>> 22), 2869860233)
  h3 = Math.imul(h1 ^ (h3 >>> 17), 951274213)
  h4 = Math.imul(h2 ^ (h4 >>> 19), 2716044179)
  return [(h1 ^ h2 ^ h3 ^ h4) >>> 0]
}

function mulberry32(a: number) {
  return function() {
    let t = (a += 0x6D2B79F5)
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

export function seededRandFromKey(key: string) {
  const [seed] = cyrb128(key)
  return mulberry32(seed)
}

export function numberFromRng(rng: () => number, max: number): number {
  return Math.floor(rng() * max) % max
}

export function pickDeterministic<T>(rng: () => number, arr: T[]): T {
  return arr[Math.floor(rng() * arr.length) % arr.length]
}

export interface GameState {
  players: number
  round: number
  category: string
  activePlayer: number | null
  revealed: boolean
  impostorIndex: number
  chosenWord: string
  impostorHint: string
  startPlayerIndex: number
  gameStarted: boolean
}

export function createGameState(players: number, round: number, category: string): GameState {
  const roomKey = `${round}#${players}#${category}`

  // Handle "Random" category by picking a random category deterministically
  let actualCategory = category
  let words = WORD_BANK[category]

  if (category === 'Random') {
    const categoryRng = seededRandFromKey(roomKey + ':cat')
    actualCategory = pickDeterministic(categoryRng, ALL_CATEGORIES)
    words = WORD_BANK[actualCategory]
  }

  const impostorIndex = numberFromRng(seededRandFromKey(roomKey + ':imp'), players)
  const chosenWord = pickDeterministic(seededRandFromKey(roomKey + ':word'), words)
  const impostorHint = getHintForWord(chosenWord)
  const startPlayerIndex = numberFromRng(seededRandFromKey(roomKey + ':start'), players)

  return {
    players,
    round,
    category: actualCategory, // Store the actual category that was selected
    activePlayer: null,
    revealed: false,
    impostorIndex,
    chosenWord,
    impostorHint,
    startPlayerIndex,
    gameStarted: false
  }
}